# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vendaonline
    networks:
      - project
    volumes:
      - .docker/local/data/db:/var/lib/mysql/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - project

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5566:5566
    env_file:
      - docker/.env
    links:
      - db
    volumes:
      - .:/go
    networks:
      - project

networks:
  project:

volumes:
  web:
  db: